[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A brainfuck interpreter written in rust"
readme = "README.md"

[dependencies]
shittyinput = "1.1.1"
